name: run-tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 9 1 * *"

jobs:
  single-node:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        go:
          - "1.19"
          - "1.20"
        clickhouse: # https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions
          - "22.3"
          - "22.8"
          - "22.12"
          - "23.1"
          - "23.2"
          - "latest"
    steps:
      - uses: actions/checkout@main

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2.1.5
        with:
          stable: false
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: |
          CLICKHOUSE_VERSION=${{ matrix.clickhouse }} make test

